import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Next-dashboard/about",
    description: "Generated by create next app",
  };
  

function AboutPage() {
  return (
    <div>AboutPage</div>
  )
}

export default AboutPage